name: C++ CI (GCC & Clang with GTest)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    name: Build & Test (${{ matrix.compiler }})
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libgtest-dev clang

      - name: Configure CMake
        run: cmake -S LA-TEST-ENV -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}

      - name: Build
        run: cmake --build build

      - name: Run Tests
        working-directory: LA-TEST-ENV
        run: ctest --test-dir ../build --output-on-failure
