# Use Ubuntu as base image
FROM ubuntu:24.04

# Avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install build tools and GCC
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    cmake \
    git \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project files
COPY . .

# Create build directory
RUN mkdir build


# Build
RUN cmake -S . -B build
RUN cmake --build build

# Run tests
CMD ["ctest", "--test-dir", "build", "--output-on-failure"]